core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('sign_in', views.sign_in, name='sign_in'),
    path('logout', views.logout_user, name='logout'),
    path('cr_profile', views.create_profile, name='cr_profile'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    patronymic = models.CharField('Отчество', max_length=30, null=True, blank=True)
    profile_picture = models.FileField('Фото профиля', upload_to='media/profile_pictures',
                                       null=True, blank=True)
    email = models.EmailField('Адрес эл. почты', max_length=30, blank=True)
    phone_number = models.CharField(max_length=11, blank=True)
    creation_dt = models.DateTimeField(null=True, blank=True, default=now())
    date_of_birth = models.DateField('Дата рождения',default=now(), blank=True, null=True)

    def __str__(self) -> str:
        return f'{self.user.first_name} {self.user.last_name}'

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

core/forms.py
from django import forms
from core import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserDisplayForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ('patronymic', 'phone_number', 'date_of_birth')

core/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout
from django.views.generic import TemplateView

from core import models, forms
from django.contrib import messages


def literally1984(request):
    if request.user.is_authenticated and not models.Profile.filter(user=request.user).exists():
        return redirect('core:cr_profile')

def sign_up(request):

    if request.method == 'POST':
        form = forms.UserCreateForm(request.POST)
        if form.is_valid():
            print(form.data)
            form.save()
            messages.success(request, f'Учётная запись создана')
            return redirect('core:home')

    context = {
        'form': forms.UserCreateForm()
    }
    return render(request=request, template_name='core/sign_up.html', context=context)


def sign_in(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('core:home')

        else:
            messages.info(request, 'Логин либо пароль введены неверно')
            return render(request=request, template_name='core/sign_in.html')

    return render(request=request, template_name='core/sign_in.html')


def logout_user(request):
    logout(request)
    return redirect('core:home')


def create_profile(request):

    if request.method == 'POST':
        form = forms.ProfileForm(request.POST)
        if form.is_valid():
            gett = models.Profile.objects.get(user=request.user),
            profile = gett[0]
            if patronymic := form.data.get('patronymic'):
                print(profile)

                profile.patronymic = patronymic
            if phone_number := form.data.get('phone_number'):
                profile.phone_number = phone_number
            if date_of_birth := form.data.get('date_of_birth'):
                profile.date_of_birth = date_of_birth

            profile.save()
            messages.success(request, f'заебись')
            return redirect('core:home')

    context = {
        'form': forms.ProfileForm()
    }
    return render(request=request, template_name='core/create_profile.html', context=context)

class Home(TemplateView):
    template_name = 'core/home.html'


core/templates/core/create_profile.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load static %}

    <link rel="stylesheet" href="{% static 'core/css/sign_in.css' %}">
    <title>6роук</title>
  </head>

  <body>

  <div class="login">
  <!-- login header -->
    <h1 id="header">Sign up in seconds</h1>
  <!-- start da login goodness -->
    <form id="form" method="post">
      {% csrf_token %}
      patr={{ form.patronymic }}<br>
      dob={{ form.date_of_birth }}<br>
      p_num={{ form.phone_number }}<br>
      {{ form.message.errors }}<br>
      <input type="submit" value="ladno!">
    </form>
  </div>

  </body>
</html>

core/templates/core/for_superusers.html

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load static %}

    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/scroll.css' %}">
    <title>Кинопоиск2</title>
  </head>

  <body>

    <div id="left-part">
      <a id="logo" class="gradiented" href="#">Кинопоиск 2</a>
      <a class="gradiented" href="{% url 'core:main_page' %}">Домой</a>
      <a class="gradiented" href="{% url 'core:movies' %}">Фильмы</a>
      <a class="gradiented" href="{% url 'core:actors' %}">Актёры</a>
      <a class="gradiented" href="{% url 'core:feedbacks' %}">Оценки</a>

    </div>

    <div class="right-part">

        <nav id="top-nav">
          {% if user.is_authenticated %}
            <span class="gradiented">{{request.user}} </span><button class="btn"><a href="{% url 'core:logout' %}">выйти</a></button>
          {% else %}
          <button class="btn"><a href="{% url 'core:sign_in' %}">войти</a></button>
          {% endif %}

      </nav>

      {% if user.is_authenticated %}
        {% if user.is_superuser %}
          {% block content%}

          {% endblock %}
        {% endif %}
      {% endif %}
    </div>
  </body>
</html>

core/templates/core/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

  {% if user.is_authenticated %}
    <span >{{request.user}} </span><button><a href="{% url 'core:logout' %}">выйти</a></button>
  {% else %}
    <button><a href="{% url 'core:sign_up' %}">зарегистрирваться</a></button>
    <button><a href="{% url 'core:sign_in' %}">войти</a></button>
  {% endif %}

    <p>отчество={{user.profile.patronymic}}</p>
    <p>номер телефофыв={{user.profile.phone_number}}</p>
    <p>дата рождле={{user.profile.date_of_birth}}</p>


</body>
</html>

core/templates/core/sign_in.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>6роук</title>
  </head>

  <body>
    <form method="post">
      {% csrf_token %}
      <p>Имя пользователя: <input type="text" name="username"></p>
          <p>Пароль: <input type="password" name="password"></p>

      <button type="submit">войти</button>
    </form>
  </body>
</html>

core/templates/core/sign_up.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load static %}

    <link rel="stylesheet" href="{% static 'core/css/sign_in.css' %}">
    <title>6роук</title>
  </head>

  <body>

  <div class="login">
  <!-- login header -->
    <h1 id="header">Sign up in seconds</h1>
  <!-- start da login goodness -->
    <form id="form" method="post">
      {% csrf_token %}
      username={{ form.username }}<br>
      mail={{ form.email }}<br>
      pawwssd={{ form.password1 }}<br>
      confirm={{ form.password2 }}<br>
      {{ form.message.errors }}<br>
      <input type="submit" value="Sign me up!">
    </form>
  </div>

  {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}


  </body>
</html>